version: '3'
services:
  musicplayer:
    container_name: php-apache
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/
    ports:
      - 8000:80
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: php-app
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASS
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    ports:
      - 8001:8080
