version: "2"
services:
  webserver:
    image: php:latest 
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /:/var/www/html
    depends_on:
      - db
    networks:
      - test
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 0111cs211163
      POSTGRES_DB: projectsdb   
      POSTGRES_USERNAME: postgres
    ports:
      - "5433:5432"